### ISSUE TITLE
Cuda 11 error

### ISSUE THREAD

**Issue by neowisard** [MeetKai/functionary#112]
Hi there!
What can i do with it error , i have a Tesla P100 (Pascal arch) and it need in Cuda 11

`root@oc2:/ai/functionary# python3 server_vllm.py --model "/ai/models/functionary-small-v2.2.q8_0.gguf" --host 0.0.0.0 --port 5000
Traceback (most recent call last):
  File "/ai/functionary/server_vllm.py", line 33, in <module>
    from vllm.engine.arg_utils import AsyncEngineArgs
  File "/usr/local/lib/python3.10/dist-packages/vllm/__init__.py", line 3, in <module>
    from vllm.engine.arg_utils import AsyncEngineArgs, EngineArgs
  File "/usr/local/lib/python3.10/dist-packages/vllm/engine/arg_utils.py", line 6, in <module>
    from vllm.config import (CacheConfig, ModelConfig, ParallelConfig,
  File "/usr/local/lib/python3.10/dist-packages/vllm/config.py", line 9, in <module>
    from vllm.utils import get_cpu_memory, is_hip
  File "/usr/local/lib/python3.10/dist-packages/vllm/utils.py", line 11, in <module>
    from vllm._C import cuda_utils
ImportError: libcudart.so.12: cannot open shared object file: No such file or directory

root@oc2:/ai/functionary# nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2022 NVIDIA Corporation
Built on Wed_Sep_21_10:33:58_PDT_2022
Cuda compilation tools, release 11.8, V11.8.89
Build cuda_11.8.r11.8/compiler.31833905_0
`

thanks in advance

**Comment by neowisard** [comment]
Sorry , it's vllm https://docs.vllm.ai/en/latest/getting_started/installation.html#install-with-pip
