### ISSUE TITLE
Work with cuda 11 GPU , as P40 etc , 6.1 arch ?

### ISSUE THREAD

**Issue by neowisard** [MeetKai/functionary#113]
Hi. Is there any way to run the API also on Pascal GPU (P40) ? 
it has TORCH_CUDA_ARCH_LIST=6.1 and supported by torch. It can use float32 .  
Unfortunately I don't see a way to run functionary 2 , the other APIs haven't integrated the functions yet.

Successfully installed functionary.
manually reinstall vllm 0.2.7 with cuda11.8 and other requirements . 

![Screenshot from 2024-02-04 22-00-06](https://github.com/MeetKai/functionary/assets/1011406/6faba2df-920f-4f27-86b8-9e459577f1c6)

`  

> Downloading https://download.pytorch.org/whl/cu118/xformers-0.0.23.post1%2Bcu118-cp310-cp310-manylinux2014_x86_64.whl (212.9 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 212.9/212.9 MB 5.8 MB/s eta 0:00:00
Requirement already satisfied: numpy in /opt/conda/envs/func/lib/python3.10/site-packages (from xformers==0.0.23.post1) (1.26.3)
Requirement already satisfied: torch==2.1.2 in /opt/conda/envs/func/lib/python3.10/site-packages (from xformers==0.0.23.post1) (2.1.2+cu118)
Requirement already satisfied: filelock in /opt/conda/envs/func/lib/python3.10/site-packages (from torch==2.1.2->xformers==0.0.23.post1) (3.13.1)
Requirement already satisfied: typing-extensions in /opt/conda/envs/func/lib/python3.10/site-packages (from torch==2.1.2->xformers==0.0.23.post1) (4.9.0)
Requirement already satisfied: sympy in /opt/conda/envs/func/lib/python3.10/site-packages (from torch==2.1.2->xformers==0.0.23.post1) (1.12)
Requirement already satisfied: networkx in /opt/conda/envs/func/lib/python3.10/site-packages (from torch==2.1.2->xformers==0.0.23.post1) (3.2.1)
Requirement already satisfied: jinja2 in /opt/conda/envs/func/lib/python3.10/site-packages (from torch==2.1.2->xformers==0.0.23.post1) (3.1.3)
Requirement already satisfied: fsspec in /opt/conda/envs/func/lib/python3.10/site-packages (from torch==2.1.2->xformers==0.0.23.post1) (2023.12.2)
Requirement already satisfied: triton==2.1.0 in /opt/conda/envs/func/lib/python3.10/site-packages (from torch==2.1.2->xformers==0.0.23.post1) (2.1.0)
Requirement already satisfied: MarkupSafe>=2.0 in /opt/conda/envs/func/lib/python3.10/site-packages (from jinja2->torch==2.1.2->xformers==0.0.23.post1) (2.1.5)
Requirement already satisfied: mpmath>=0.19 in /opt/conda/envs/func/lib/python3.10/site-packages (from sympy->torch==2.1.2->xformers==0.0.23.post1) (1.3.0)
Installing collected packages: xformers
  Attempting uninstall: xformers
    Found existing installation: xformers 0.0.23.post1
    Uninstalling xformers-0.0.23.post1:
      Successfully uninstalled xformers-0.0.23.post1
Successfully installed xformers-0.0.23.post1+cu118

`

> NFO 02-04 18:59:20 server_vllm.py:542] args: Namespace(host='0.0.0.0', port=5000, allow_credentials=False, allowed_origins=['*'], allowed_methods=['*'], allowed_headers=['*'], served_model_name=None, grammar_sampling=True, model='meetkai/functionary-small-v2.2', tokenizer=None, revision=None, tokenizer_revision=None, tokenizer_mode='auto', trust_remote_code=False, download_dir='/ai/models', load_format='auto', dtype='float32', max_model_len=None, worker_use_ray=False, pipeline_parallel_size=1, tensor_parallel_size=2, max_parallel_loading_workers=None, block_size=16, seed=0, swap_space=4, gpu_memory_utilization=0.9, max_num_batched_tokens=None, max_num_seqs=256, max_paddings=256, disable_log_stats=False, quantization=None, enforce_eager=False, max_context_len_to_capture=8192, engine_use_ray=False, disable_log_requests=False, max_log_len=None)
2024-02-04 18:59:24,783	INFO worker.py:1724 -- Started a local Ray instance.
INFO 02-04 18:59:25 llm_engine.py:70] Initializing an LLM engine with config: model='meetkai/functionary-small-v2.2', tokenizer='meetkai/functionary-small-v2.2', tokenizer_mode=auto, revision=None, tokenizer_revision=None, trust_remote_code=False, dtype=torch.float32, max_seq_len=32768, download_dir='/ai/models', load_format=auto, tensor_parallel_size=2, quantization=None, enforce_eager=False, seed=0)
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
Traceback (most recent call last):
  File "/ai/functionary/server_vllm.py", line 550, in <module>
    engine = AsyncLLMEngine.from_engine_args(engine_args)
  File "/ai/functionary/functionary/vllm_monkey_patch/async_llm_engine.py", line 627, in from_engine_args
    engine = cls(
  File "/ai/functionary/functionary/vllm_monkey_patch/async_llm_engine.py", line 344, in __init__
    self.engine = self._init_engine(*args, **kwargs)
  File "/ai/functionary/functionary/vllm_monkey_patch/async_llm_engine.py", line 387, in _init_engine
    return engine_class(*args, **kwargs)
  File "/opt/conda/envs/func/lib/python3.10/site-packages/vllm/engine/llm_engine.py", line 114, in __init__
    self._init_cache()
  File "/opt/conda/envs/func/lib/python3.10/site-packages/vllm/engine/llm_engine.py", line 262, in _init_cache
    num_blocks = self._run_workers(
  File "/opt/conda/envs/func/lib/python3.10/site-packages/vllm/engine/llm_engine.py", line 795, in _run_workers
    driver_worker_output = getattr(self.driver_worker,
  File "/opt/conda/envs/func/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/opt/conda/envs/func/lib/python3.10/site-packages/vllm/worker/worker.py", line 96, in profile_num_available_blocks
    self.model_runner.profile_run()
  File "/opt/conda/envs/func/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/opt/conda/envs/func/lib/python3.10/site-packages/vllm/worker/model_runner.py", line 494, in profile_run
    self.execute_model(seqs, kv_caches)
  File "/opt/conda/envs/func/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/opt/conda/envs/func/lib/python3.10/site-packages/vllm/worker/model_runner.py", line 453, in execute_model
    hidden_states = model_executable(
  File "/opt/conda/envs/func/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/opt/conda/envs/func/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/opt/conda/envs/func/lib/python3.10/site-packages/vllm/model_executor/models/mistral.py", line 282, in forward
    hidden_states = self.model(input_ids, positions, kv_caches,
  File "/opt/conda/envs/func/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/opt/conda/envs/func/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/opt/conda/envs/func/lib/python3.10/site-packages/vllm/model_executor/models/mistral.py", line 250, in forward
    hidden_states, residual = layer(
  File "/opt/conda/envs/func/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/opt/conda/envs/func/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/opt/conda/envs/func/lib/python3.10/site-packages/vllm/model_executor/models/mistral.py", line 203, in forward
    hidden_states = self.self_attn(
  File "/opt/conda/envs/func/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/opt/conda/envs/func/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/opt/conda/envs/func/lib/python3.10/site-packages/vllm/model_executor/models/mistral.py", line 153, in forward
    attn_output = self.attn(q, k, v, k_cache, v_cache, input_metadata)
  File "/opt/conda/envs/func/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/opt/conda/envs/func/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/opt/conda/envs/func/lib/python3.10/site-packages/vllm/model_executor/layers/attention.py", line 146, in forward
    out = xops.memory_efficient_attention_forward(
  File "/opt/conda/envs/func/lib/python3.10/site-packages/xformers/ops/fmha/__init__.py", line 244, in memory_efficient_attention_forward
    return _memory_efficient_attention_forward(
  File "/opt/conda/envs/func/lib/python3.10/site-packages/xformers/ops/fmha/__init__.py", line 341, in _memory_efficient_attention_forward
    out, *_ = op.apply(inp, needs_gradient=False)
  File "/opt/conda/envs/func/lib/python3.10/site-packages/xformers/ops/fmha/cutlass.py", line 243, in apply
    cls.apply_bmhk(
  File "/opt/conda/envs/func/lib/python3.10/site-packages/xformers/ops/fmha/cutlass.py", line 266, in apply_bmhk
    out, lse, rng_seed, rng_offset = cls.OPERATOR(
  File "/opt/conda/envs/func/lib/python3.10/site-packages/torch/_ops.py", line 692, in __call__
    return self._op(*args, **kwargs or {})
RuntimeError: CUDA error: no kernel image is available for execution on the device
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

> /ai/functionary# python3 server_vllm.py --model "meetkai/functionary-small-v2.2" --tensor-parallel-size 2  --host 0.0.0.0 --port 5000 --dtype auto --download-dir /ai/models 

>    ValueError: Bfloat16 is only supported on GPUs with compute capability of at least 8.0. Your Tesla P40 GPU has compute capability 6.1.

**Comment by neowisard** [comment]
https://github.com/vllm-project/vllm/issues/1374
