### ISSUE TITLE
Internal Server Error

### ISSUE THREAD

**Issue by alexandergagliano** [MeetKai/functionary#116]
Hello!

I am setting up a small SQL LLM (`functionary-small-v2.2` through a vLLM.py server) with functionary. The LLM has two tools that should be run sequentially, a vector retrieval tool for similar SQL queries and the sql query function itself. The code worked fine for the retrieval tool alone, but when I try to feed the results back into the model I get the following error:

```
Future exception was never retrieved
future: <Future finished exception=KeyError('add_predefined_fns')>
Traceback (most recent call last):
  File "/n/holyscratch01/iaifi_lab/agagliano/LLMs/functionary/functionary/vllm_monkey_patch/async_llm_engine.py", line 41, in _raise_exception_on_finish
    task.result()
  File "/n/holyscratch01/iaifi_lab/agagliano/LLMs/functionary/functionary/vllm_monkey_patch/async_llm_engine.py", line 429, in run_engine_loop
    has_requests_in_progress = await self.engine_step()
  File "/n/holyscratch01/iaifi_lab/agagliano/LLMs/functionary/functionary/vllm_monkey_patch/async_llm_engine.py", line 407, in engine_step
    request_outputs = await self.engine.step_async()
  File "/n/holyscratch01/iaifi_lab/agagliano/LLMs/functionary/functionary/vllm_monkey_patch/async_llm_engine.py", line 253, in step_async
    ) = prompt_template.grammar_sample(
  File "/n/holyscratch01/iaifi_lab/agagliano/LLMs/functionary/functionary/prompt_template/base_template.py", line 293, in grammar_sample
    if gen_state["stage"] == "function" and gen_state["add_predefined_fns"] is True:
KeyError: 'add_predefined_fns'
INFO 02-09 13:52:58 llm_engine.py:653] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 22.4 tokens/s, Running: 1 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 15.4%, CPU KV cache usage: 0.0%
Exception in callback functools.partial(<function _raise_exception_on_finish at 0x1537ac45d2d0>, request_tracker=<functionary.vllm_monkey_patch.async_llm_engine.RequestTracker object at 0x1537ac420b80>)
handle: <Handle functools.partial(<function _raise_exception_on_finish at 0x1537ac45d2d0>, request_tracker=<functionary.vllm_monkey_patch.async_llm_engine.RequestTracker object at 0x1537ac420b80>)>
Traceback (most recent call last):
  File "/n/holyscratch01/iaifi_lab/agagliano/LLMs/functionary/functionary/vllm_monkey_patch/async_llm_engine.py", line 41, in _raise_exception_on_finish
    task.result()
  File "/n/holyscratch01/iaifi_lab/agagliano/LLMs/functionary/functionary/vllm_monkey_patch/async_llm_engine.py", line 429, in run_engine_loop
    has_requests_in_progress = await self.engine_step()
  File "/n/holyscratch01/iaifi_lab/agagliano/LLMs/functionary/functionary/vllm_monkey_patch/async_llm_engine.py", line 407, in engine_step
    request_outputs = await self.engine.step_async()
  File "/n/holyscratch01/iaifi_lab/agagliano/LLMs/functionary/functionary/vllm_monkey_patch/async_llm_engine.py", line 253, in step_async
    ) = prompt_template.grammar_sample(
  File "/n/holyscratch01/iaifi_lab/agagliano/LLMs/functionary/functionary/prompt_template/base_template.py", line 293, in grammar_sample
    if gen_state["stage"] == "function" and gen_state["add_predefined_fns"] is True:
KeyError: 'add_predefined_fns'

.
.
.

  File "/n/holyscratch01/iaifi_lab/agagliano/LLMs/functionary/functionary/vllm_monkey_patch/async_llm_engine.py", line 45, in _raise_exception_on_finish
    raise AsyncEngineDeadError(
functionary.vllm_monkey_patch.async_llm_engine.AsyncEngineDeadError: Task finished unexpectedly. This should never happen! Please open an issue on Github. See stack trace above for the actual cause.

```

The relevant code is below:
```
def execute_tool_call(message):
    #start with one for now
    func = message.tool_calls[0].function
    if func.name == "sql_get_similar_examples":
        data_question = json.loads(func.arguments)["data_question"]
        results = get_similar_examples(data_question)
    else:
        results = f"Error: function {message.tool_calls[0].name} does not exist"
    return results

while len(assistant_msg.tool_calls)>0:
    results = execute_tool_call(assistant_msg)
    messages.append({"role": "assistant", "name": assistant_msg.tool_calls[0].function.name, "content": assistant_msg.tool_calls[0].function.arguments})
    messages.append({"role": "function", "name": assistant_msg.tool_calls[0].function.name, "content": str(results)})

    print(messages[-1])

    assistant_msg = client.chat.completions.create(
        model="meetkai/functionary-small-v2.2",
        messages=messages,
        tools=tools,
        tool_choice="auto",
        #temperature=0.0,
    ).choices[0].message
```

Any thoughts on how to resolve the issue? Thanks!

**Comment by jeffrey-fong** [comment]
Hi, can you try the following options:
1. This bug was present previously and had been fixed already. You could be on an older commit. Try again with the latest commit in main branch.
2. If you're in the latest commit already, can you disable grammar sampling [here](https://github.com/MeetKai/functionary/blob/main/server_vllm.py#L518)? The bug is in our vLLM engine monkey patch to allow grammar sampling so your use case should work without grammar sampling, albeit the function and argument names may not be 100% accurate anymore.

If option 1 fails, do you mind sharing with me how do the function outputs look like for the 2 functions above and also the function definitions for them? This is to help me to try to reproduce the error and pinpoint the edge cases I may have left out. I tried with the following simple example and it works.
```python
def get_temperature(city):
    return "-1 degrees celcius"


def advise_clothing(temperature):
    return "winter wear"


def execute_tool_call(message):
    # start with one for now
    func = message.tool_calls[0].function
    if func.name == "get_temperature":
        city = json.loads(func.arguments)["city"]
        results = get_temperature(city)
    elif func.name == "advise_clothing":
        temperature = json.loads(func.arguments)["temperature"]
        results = advise_clothing(temperature)
    else:
        results = f"Error: function {message.tool_calls[0].name} does not exist"
    return results


messages = [
    {
        "role": "user",
        "content": "What should I wear in Toronto?",
    }
]
client = OpenAI(base_url="http://localhost:8000/v1", api_key="test")
tools = [
    {
        "type": "function",
        "function": {
            "name": "get_temperature",
            "description": "Gets the temperature for the particular city",
            "parameters": {
                "type": "object",
                "properties": {
                    "city": {
                        "type": "string",
                        "description": "The city of interest. E.g.: New York City, NY",
                    }
                },
                "required": ["city"],
            },
        },
    },
    {
        "type": "function",
        "function": {
            "name": "advise_clothing",
            "description": "Provides advice on what kind of clothing to be worn depending on the temperature",
            "parameters": {
                "type": "object",
                "properties": {
                    "temperature": {
                        "type": "string",
                        "description": "The temperature provided. Clothing advice will be provided based on the temperature",
                    }
                },
                "required": ["temperature"],
            },
        },
    },
]

while True:
    assistant_msg = (
        client.chat.completions.create(
            model="meetkai/functionary-small-v2.2",
            messages=messages,
            tools=tools,
            tool_choice="auto",
            # temperature=0.0,
        )
        .choices[0]
        .message
    )
    if assistant_msg.tool_calls is not None and len(assistant_msg.tool_calls) > 0:
        results = execute_tool_call(assistant_msg)
        messages.append(
            {
                "role": "assistant",
                "name": assistant_msg.tool_calls[0].function.name,
                "content": assistant_msg.tool_calls[0].function.arguments,
            }
        )
        messages.append(
            {
                "role": "tool",
                "name": assistant_msg.tool_calls[0].function.name,
                "content": str(results),
            }
        )
        print(
            f"{assistant_msg.tool_calls[0].function.name} -> {assistant_msg.tool_calls[0].function.arguments}"
        )
        print(f"tool returned -> {results}")
    else:
        print(assistant_msg.content)
        break

```

**Comment by alexandergagliano** [comment]
Looks like I was indeed on an older commit, and your example (and mine too) work now. Thanks very much!
