### ISSUE TITLE
No module named 'lmformatenforcer'

### ISSUE THREAD

**Issue by Mars-1990** [MeetKai/functionary#197]
Traceback (most recent call last):
  File "/home/hirpa/fzq/2024/code/functionary/server_vllm.py", line 39, in <module>
    from functionary.vllm_inference import process_chat_completion
  File "/home/hirpa/fzq/2024/code/functionary/functionary/vllm_inference.py", line 13, in <module>
    from functionary.inference import enforce_tool_choice, prepare_messages_for_inference
  File "/home/hirpa/fzq/2024/code/functionary/functionary/inference.py", line 4, in <module>
    from lmformatenforcer import CharacterLevelParser, JsonSchemaParser
ModuleNotFoundError: No module named 'lmformatenforcer'

**Comment by jeffrey-fong** [comment]
Can you try again after running `pip install requirements.txt` to download the latest dependencies? lm-format-enforcer is one of the dependencies of vLLM and should be installed when installing the vLLM version (v0.4.1) in our `requirements.txt`. I believe you should be using an older version of vLLM instead. Let me know if the problem persists.
