### ISSUE TITLE
Streaming with vLLM doesn't seem to work

### ISSUE THREAD

**Issue by morgendigital** [MeetKai/functionary#200]
I'm trying to use functionary (v2.4-medium-AWQ) with the vLLM OpenAI-compatible endpoint, however it seems that streaming doesn't work on the OpenAI-compatible Endpoint.

I have written a short script to evaluate if everything is working correctly, and it works perfectly without streaming, but with streaming, I don't get any output or I get an error when tools are involved.

# ✅ Without Streaming

### Python Code
```
from openai import OpenAI

client = OpenAI(base_url="http://localhost:8000/v1", api_key="some-key")

completion = client.chat.completions.create(
    model="meetkai/functionary-medium-v2.4-AWQ",
    messages=[{"role": "user",
            "content": "Hey, how are you doing?"}
    ],
    tools=[{
            "type": "function",
            "function": {
                "name": "get_current_weather",
                "description": "Get the current weather",
                "parameters": {
                    "type": "object",
                    "properties": {
                        "location": {
                            "type": "string",
                            "description": "The city and state, e.g. San Francisco, CA"
                        }
                    },
                    "required": ["location"]
                }
            }
        }],
    tool_choice="auto"
)

print(completion)
```

### Response
```
ChatCompletion(id='cmpl-67bed551b2194741ae7325493a553abe', choices=[Choice(finish_reason='stop', index=0, logprobs=None, message=ChatCompletionMessage(content="I'm a computer program, so I don't experience emotions or have a personal life. However, I'm here to assist you with information, answer questions, and provide information to the best of my knowledge and abilities. How can I assist you today?", role='assistant', function_call=None, tool_calls=[], tool_call_id=None, name=None))], created=1717176536, model='meetkai/functionary-medium-v2.4-AWQ', object='chat.completion', system_fingerprint=None, usage=CompletionUsage(completion_tokens=58, prompt_tokens=141, total_tokens=199))
```

# 🛑 With Streaming

### Python code
```
from openai import OpenAI

client = OpenAI(base_url="http://localhost:8000/v1", api_key="some-key")

completion = client.chat.completions.create(
    model="meetkai/functionary-medium-v2.4-AWQ",
    messages=[{"role": "user",
            "content": "Hey, how are you doing?"}
    ],
    tools=[{
            "type": "function",
            "function": {
                "name": "get_current_weather",
                "description": "Get the current weather",
                "parameters": {
                    "type": "object",
                    "properties": {
                        "location": {
                            "type": "string",
                            "description": "The city and state, e.g. San Francisco, CA"
                        }
                    },
                    "required": ["location"]
                }
            }
        }],
    tool_choice="auto",
    stream=True
)

for chunk in completion:
    print(chunk.choices[0].delta)
```

### Response
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/httpx/_transports/default.py", line 69, in map_httpcore_exceptions
    yield
  File "/usr/local/lib/python3.10/dist-packages/httpx/_transports/default.py", line 113, in __iter__
    for part in self._httpcore_stream:
  File "/usr/local/lib/python3.10/dist-packages/httpcore/_sync/connection_pool.py", line 367, in __iter__
    raise exc from None
  File "/usr/local/lib/python3.10/dist-packages/httpcore/_sync/connection_pool.py", line 363, in __iter__
    for part in self._stream:
  File "/usr/local/lib/python3.10/dist-packages/httpcore/_sync/http11.py", line 349, in __iter__
    raise exc
  File "/usr/local/lib/python3.10/dist-packages/httpcore/_sync/http11.py", line 341, in __iter__
    for chunk in self._connection._receive_response_body(**kwargs):
  File "/usr/local/lib/python3.10/dist-packages/httpcore/_sync/http11.py", line 210, in _receive_response_body
    event = self._receive_event(timeout=timeout)
  File "/usr/local/lib/python3.10/dist-packages/httpcore/_sync/http11.py", line 220, in _receive_event
    with map_exceptions({h11.RemoteProtocolError: RemoteProtocolError}):
  File "/usr/lib/python3.10/contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/usr/local/lib/python3.10/dist-packages/httpcore/_exceptions.py", line 14, in map_exceptions
    raise to_exc(exc) from exc
httpcore.RemoteProtocolError: peer closed connection without sending complete message body (incomplete chunked read)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/root/tests/vllm-mixed-functions-streaming.py", line 31, in <module>
    for chunk in completion:
  File "/usr/local/lib/python3.10/dist-packages/openai/_streaming.py", line 46, in __iter__
    for item in self._iterator:
  File "/usr/local/lib/python3.10/dist-packages/openai/_streaming.py", line 58, in __stream__
    for sse in iterator:
  File "/usr/local/lib/python3.10/dist-packages/openai/_streaming.py", line 50, in _iter_events
    yield from self._decoder.iter_bytes(self.response.iter_bytes())
  File "/usr/local/lib/python3.10/dist-packages/openai/_streaming.py", line 280, in iter_bytes
    for chunk in self._iter_chunks(iterator):
  File "/usr/local/lib/python3.10/dist-packages/openai/_streaming.py", line 291, in _iter_chunks
    for chunk in iterator:
  File "/usr/local/lib/python3.10/dist-packages/httpx/_models.py", line 829, in iter_bytes
    for raw_bytes in self.iter_raw():
  File "/usr/local/lib/python3.10/dist-packages/httpx/_models.py", line 883, in iter_raw
    for raw_stream_bytes in self.stream:
  File "/usr/local/lib/python3.10/dist-packages/httpx/_client.py", line 126, in __iter__
    for chunk in self._stream:
  File "/usr/local/lib/python3.10/dist-packages/httpx/_transports/default.py", line 112, in __iter__
    with map_httpcore_exceptions():
  File "/usr/lib/python3.10/contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/usr/local/lib/python3.10/dist-packages/httpx/_transports/default.py", line 86, in map_httpcore_exceptions
    raise mapped_exc(message) from exc
httpx.RemoteProtocolError: peer closed connection without sending complete message body (incomplete chunked read)
```

### Log from vLLM
```
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/uvicorn/protocols/http/httptools_impl.py", line 426, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/usr/local/lib/python3.10/dist-packages/uvicorn/middleware/proxy_headers.py", line 84, in __call__
    return await self.app(scope, receive, send)
  File "/usr/local/lib/python3.10/dist-packages/fastapi/applications.py", line 1106, in __call__
    await super().__call__(scope, receive, send)
  File "/usr/local/lib/python3.10/dist-packages/starlette/applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.10/dist-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/usr/local/lib/python3.10/dist-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/usr/local/lib/python3.10/dist-packages/starlette/middleware/cors.py", line 83, in __call__
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.10/dist-packages/starlette/middleware/exceptions.py", line 79, in __call__
    raise exc
  File "/usr/local/lib/python3.10/dist-packages/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "/usr/local/lib/python3.10/dist-packages/fastapi/middleware/asyncexitstack.py", line 20, in __call__
    raise e
  File "/usr/local/lib/python3.10/dist-packages/fastapi/middleware/asyncexitstack.py", line 17, in __call__
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.10/dist-packages/starlette/routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "/usr/local/lib/python3.10/dist-packages/starlette/routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.10/dist-packages/starlette/routing.py", line 69, in app
    await response(scope, receive, send)
  File "/usr/local/lib/python3.10/dist-packages/starlette/responses.py", line 270, in __call__
    async with anyio.create_task_group() as task_group:
  File "/usr/local/lib/python3.10/dist-packages/anyio/_backends/_asyncio.py", line 597, in __aexit__
    raise exceptions[0]
  File "/usr/local/lib/python3.10/dist-packages/starlette/responses.py", line 273, in wrap
    await func()
  File "/usr/local/lib/python3.10/dist-packages/starlette/responses.py", line 262, in stream_response
    async for chunk in self.body_iterator:
  File "/root/functionary/functionary/vllm_inference.py", line 254, in completion_stream_generator
    async for response in generate_openai_format_from_stream_async(
  File "/root/functionary/functionary/inference_stream.py", line 238, in generate_openai_format_from_stream_async
    state, response = prompt_template.update_response_state_from_delta_text(
  File "/root/functionary/functionary/prompt_template/prompt_template_v2.py", line 446, in update_response_state_from_delta_text
    func_name = tool_choice.function.name
AttributeError: 'str' object has no attribute 'function'
INFO 05-31 17:30:19 async_llm_engine.py:120] Finished request cmpl-6dda581d394e4fa3a10189d83cbb13fa.
```

# 🛑 With Streaming, but with Tools removed 
Here, I get a slightly different error.

### Python Code
```
from openai import OpenAI

client = OpenAI(base_url="http://localhost:8000/v1", api_key="some-key")

completion = client.chat.completions.create(
    model="meetkai/functionary-medium-v2.4-AWQ",
    messages=[{"role": "user",
            "content": "Hey, how are you doing?"}
    ],
    stream=True
)

for chunk in completion:
    print(chunk.choices[0].delta)
```

### Response
```
ChoiceDelta(content=None, function_call=None, role=None, tool_calls=None)
```

### vLLM Output
```
INFO:     127.0.0.1:41982 - "POST /v1/chat/completions HTTP/1.1" 200 OK
INFO 05-31 17:34:35 async_llm_engine.py:524] Received request cmpl-b548002a12f04b12b7f2a9bbc67634a2: prompt: None, sampling_params: SamplingParams(n=1, best_of=1, presence_penalty=0.0, frequency_penalty=0.0, repetition_penalty=1.0, temperature=0.6, top_p=1.0, top_k=-1, min_p=0.0, seed=None, use_beam_search=False, length_penalty=1.0, early_stopping=False, stop=[], stop_token_ids=[32003], include_stop_str_in_output=False, ignore_eos=False, max_tokens=512, min_tokens=0, logprobs=None, prompt_logprobs=None, skip_special_tokens=False, spaces_between_special_tokens=True, truncate_prompt_tokens=None), prompt_token_ids: [1, 32000, 1587, 13, 32001, 544, 13, 32002, 589, 10731, 286, 908, 20343, 369, 1023, 347, 1987, 739, 4892, 28723, 13, 14147, 5572, 371, 13, 13, 28752, 589, 4772, 5572, 13, 32000, 1587, 13, 32001, 544, 13, 32002, 330, 10706, 1444, 264, 13903, 2188, 304, 396, 18278, 10895, 13892, 28723, 415, 13892, 5212, 10865, 28725, 10537, 28725, 304, 27057, 11194, 298, 272, 2188, 28742, 28713, 4224, 28723, 415, 13892, 6470, 5572, 395, 7658, 2787, 739, 4892, 13, 32000, 2188, 13, 32001, 544, 13, 32002, 17162, 28725, 910, 460, 368, 2548, 28804, 13, 32000, 13892, 13, 32001, 544, 13, 32002], lora_request: None.
INFO 05-31 17:34:35 metrics.py:229] Avg prompt throughput: 0.4 tokens/s, Avg generation throughput: 0.2 tokens/s, Running: 1 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 0.1%, CPU KV cache usage: 0.0%
INFO 05-31 17:34:37 async_llm_engine.py:120] Finished request cmpl-b548002a12f04b12b7f2a9bbc67634a2.
INFO 05-31 17:34:37 async_llm_engine.py:154] Aborted request cmpl-b548002a12f04b12b7f2a9bbc67634a2.
```

**Comment by khai-meetkai** [comment]
@morgendigital  Thank you for reporting this issue, we are fixing this in a PR, will let you know when it is done

**Comment by khai-meetkai** [comment]
@morgendigital We have merged the PR fixing your issue, can you clone the latest code and try again?

**Comment by morgendigital** [comment]
Thank you very much @khai-meetkai , will check it later today!

**Comment by localmind-ai** [comment]
@khai-meetkai works flawlessly, thank you very much! 👍 Will close it now.

**Comment by morgendigital** [comment]
Thank you @khai-meetkai - works flawlessly! Will close this issue now.
