### ISSUE TITLE
Failed to import transformers.generation.utils; module 'numpy' has no attribute 'object'

### ISSUE THREAD

**Issue by HuanzhiMao** [MeetKai/functionary#225]
I run this command on python3.10.12, and get the following error. 
`python3 server_vllm.py --model "meetkai/functionary-medium-v2.4" --max-model-len 8192 --tensor-parallel-size 2`

```
/usr/lib/python3/dist-packages/onnx/mapping.py:25: FutureWarning: In the future `np.object` will be defined as the corresponding NumPy scalar.
  int(TensorProto.STRING): np.dtype(np.object)
Traceback (most recent call last):
  File "/home/eecs/huanzhimao/.local/lib/python3.10/site-packages/transformers/utils/import_utils.py", line 1510, in _get_module
    return importlib.import_module("." + module_name, self.__name__)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/eecs/huanzhimao/.local/lib/python3.10/site-packages/transformers/generation/utils.py", line 94, in <module>
    from accelerate.hooks import AlignDevicesHook, add_hook_to_module
  File "/home/eecs/huanzhimao/.local/lib/python3.10/site-packages/accelerate/__init__.py", line 3, in <module>
    from .accelerator import Accelerator
  File "/home/eecs/huanzhimao/.local/lib/python3.10/site-packages/accelerate/accelerator.py", line 35, in <module>
    from .checkpointing import load_accelerator_state, load_custom_state, save_accelerator_state, save_custom_state
  File "/home/eecs/huanzhimao/.local/lib/python3.10/site-packages/accelerate/checkpointing.py", line 24, in <module>
    from .utils import (
  File "/home/eecs/huanzhimao/.local/lib/python3.10/site-packages/accelerate/utils/__init__.py", line 132, in <module>
    from .fsdp_utils import load_fsdp_model, load_fsdp_optimizer, save_fsdp_model, save_fsdp_optimizer
  File "/home/eecs/huanzhimao/.local/lib/python3.10/site-packages/accelerate/utils/fsdp_utils.py", line 24, in <module>
    import torch.distributed.checkpoint as dist_cp
  File "/home/eecs/huanzhimao/.local/lib/python3.10/site-packages/torch/distributed/checkpoint/__init__.py", line 2, in <module>
    from .default_planner import DefaultLoadPlanner, DefaultSavePlanner
  File "/home/eecs/huanzhimao/.local/lib/python3.10/site-packages/torch/distributed/checkpoint/default_planner.py", line 13, in <module>
    from torch.distributed._tensor import DTensor
  File "/home/eecs/huanzhimao/.local/lib/python3.10/site-packages/torch/distributed/_tensor/__init__.py", line 6, in <module>
    import torch.distributed._tensor.ops
  File "/home/eecs/huanzhimao/.local/lib/python3.10/site-packages/torch/distributed/_tensor/ops/__init__.py", line 2, in <module>
    from .embedding_ops import *  # noqa: F403
  File "/home/eecs/huanzhimao/.local/lib/python3.10/site-packages/torch/distributed/_tensor/ops/embedding_ops.py", line 8, in <module>
    import torch.distributed._functional_collectives as funcol
  File "/home/eecs/huanzhimao/.local/lib/python3.10/site-packages/torch/distributed/_functional_collectives.py", line 12, in <module>
    from . import _functional_collectives_impl as fun_col_impl
  File "/home/eecs/huanzhimao/.local/lib/python3.10/site-packages/torch/distributed/_functional_collectives_impl.py", line 36, in <module>
    from torch._dynamo import assume_constant_result
  File "/home/eecs/huanzhimao/.local/lib/python3.10/site-packages/torch/_dynamo/__init__.py", line 2, in <module>
    from . import convert_frame, eval_frame, resume_execution
  File "/home/eecs/huanzhimao/.local/lib/python3.10/site-packages/torch/_dynamo/convert_frame.py", line 40, in <module>
    from . import config, exc, trace_rules
  File "/home/eecs/huanzhimao/.local/lib/python3.10/site-packages/torch/_dynamo/trace_rules.py", line 50, in <module>
    from .variables import (
  File "/home/eecs/huanzhimao/.local/lib/python3.10/site-packages/torch/_dynamo/variables/__init__.py", line 34, in <module>
    from .higher_order_ops import (
  File "/home/eecs/huanzhimao/.local/lib/python3.10/site-packages/torch/_dynamo/variables/higher_order_ops.py", line 13, in <module>
    import torch.onnx.operators
  File "/home/eecs/huanzhimao/.local/lib/python3.10/site-packages/torch/onnx/__init__.py", line 59, in <module>
    from ._internal.onnxruntime import (
  File "/home/eecs/huanzhimao/.local/lib/python3.10/site-packages/torch/onnx/_internal/onnxruntime.py", line 36, in <module>
    import onnx
  File "/usr/lib/python3/dist-packages/onnx/__init__.py", line 15, in <module>
    import onnx.helper  # noqa
  File "/usr/lib/python3/dist-packages/onnx/helper.py", line 14, in <module>
    from onnx import mapping
  File "/usr/lib/python3/dist-packages/onnx/mapping.py", line 25, in <module>
    int(TensorProto.STRING): np.dtype(np.object)
  File "/home/eecs/huanzhimao/.local/lib/python3.10/site-packages/numpy/__init__.py", line 324, in __getattr__
    raise AttributeError(__former_attrs__[attr])
AttributeError: module 'numpy' has no attribute 'object'.
`np.object` was a deprecated alias for the builtin `object`. To avoid this error in existing code, use `object` by itself. Doing this will not modify any behavior and is safe. 
The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
    https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations. Did you mean: 'object_'?

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/eecs/huanzhimao/.local/lib/python3.10/site-packages/transformers/utils/import_utils.py", line 1510, in _get_module
    return importlib.import_module("." + module_name, self.__name__)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/eecs/huanzhimao/.local/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 41, in <module>
    from ...modeling_utils import PreTrainedModel
  File "/home/eecs/huanzhimao/.local/lib/python3.10/site-packages/transformers/modeling_utils.py", line 45, in <module>
    from .generation import GenerationConfig, GenerationMixin
  File "<frozen importlib._bootstrap>", line 1075, in _handle_fromlist
  File "/home/eecs/huanzhimao/.local/lib/python3.10/site-packages/transformers/utils/import_utils.py", line 1500, in __getattr__
    module = self._get_module(self._class_to_module[name])
  File "/home/eecs/huanzhimao/.local/lib/python3.10/site-packages/transformers/utils/import_utils.py", line 1512, in _get_module
    raise RuntimeError(
RuntimeError: Failed to import transformers.generation.utils because of the following error (look up to see its traceback):
module 'numpy' has no attribute 'object'.
`np.object` was a deprecated alias for the builtin `object`. To avoid this error in existing code, use `object` by itself. Doing this will not modify any behavior and is safe. 
The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
    https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/data/huanzhimao/functionary/server_vllm.py", line 34, in <module>
    from functionary.vllm_inference import process_chat_completion
  File "/data/huanzhimao/functionary/functionary/vllm_inference.py", line 14, in <module>
    from functionary.inference_stream import generate_openai_format_from_stream_async
  File "/data/huanzhimao/functionary/functionary/inference_stream.py", line 6, in <module>
    from transformers import LlamaForCausalLM, LlamaTokenizer
  File "<frozen importlib._bootstrap>", line 1075, in _handle_fromlist
  File "/home/eecs/huanzhimao/.local/lib/python3.10/site-packages/transformers/utils/import_utils.py", line 1501, in __getattr__
    value = getattr(module, name)
  File "/home/eecs/huanzhimao/.local/lib/python3.10/site-packages/transformers/utils/import_utils.py", line 1500, in __getattr__
    module = self._get_module(self._class_to_module[name])
  File "/home/eecs/huanzhimao/.local/lib/python3.10/site-packages/transformers/utils/import_utils.py", line 1512, in _get_module
    raise RuntimeError(
RuntimeError: Failed to import transformers.models.llama.modeling_llama because of the following error (look up to see its traceback):
Failed to import transformers.generation.utils because of the following error (look up to see its traceback):
module 'numpy' has no attribute 'object'.
`np.object` was a deprecated alias for the builtin `object`. To avoid this error in existing code, use `object` by itself. Doing this will not modify any behavior and is safe. 
The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
    https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
```

**Comment by jeffrey-fong** [comment]
Hi, can you try again in a new environment after installing the dependencies? It seems like you have dependency conflicts.
```shell
python3 -m venv venv
source venv/bin/activate
pip install -r requirements.txt
python3 server_vllm.py --model "meetkai/functionary-medium-v2.4" --max-model-len 8192 --tensor-parallel-size 2
```

**Comment by HuanzhiMao** [comment]
Thanks for the reply @jeffrey-fong. I created a new conda environment and everything works now.

I'm wondering, will it be fine if I use `float16` instead of `bfloat16`?

```
ValueError: Bfloat16 is only supported on GPUs with compute capability of at least 8.0. Your Tesla V100-SXM2-32GB-LS GPU has compute capability 7.0. You can use float16 instead by explicitly setting the`dtype` flag in CLI, for example: --dtype=half.
```

**Comment by jeffrey-fong** [comment]
@HuanzhiMao I think `float16` should be fine for inference. We haven't tested this but there may be very slight performance degradation due to the lower precision.
