### ISSUE TITLE
CUDA Out of memory

### ISSUE THREAD

**Issue by tonylampada** [MeetKai/functionary#61]
I'm trying to run this on a AWS instance g4dn.xlarge instance (trying with different parameters)

any tips for me?

```
python3 server_vllm.py --model "meetkai/functionary-7b-v1.4" --host 0.0.0.0 --dtype float --gpu-memory-utilization .5 --block-size 8
INFO 11-26 12:46:09 llm_engine.py:72] Initializing an LLM engine with config: model='meetkai/functionary-7b-v1.4', tokenizer='meetkai/functionary-7b-v1.4', tokenizer_mode=auto, revision=None, tokenizer_revision=None, trust_remote_code=False, dtype=torch.float32, max_seq_len=32768, download_dir=None, load_format=auto, tensor_parallel_size=1, quantization=None, seed=0)
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
Traceback (most recent call last):
  File "/home/ubuntu/functionary/server_vllm.py", line 362, in <module>
    engine = AsyncLLMEngine.from_engine_args(engine_args)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/vllm/engine/async_llm_engine.py", line 487, in from_engine_args
    engine = cls(engine_args.worker_use_ray,
  File "/home/ubuntu/.local/lib/python3.10/site-packages/vllm/engine/async_llm_engine.py", line 270, in __init__
    self.engine = self._init_engine(*args, **kwargs)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/vllm/engine/async_llm_engine.py", line 306, in _init_engine
    return engine_class(*args, **kwargs)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/vllm/engine/llm_engine.py", line 110, in __init__
    self._init_workers(distributed_init_method)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/vllm/engine/llm_engine.py", line 142, in _init_workers
    self._run_workers(
  File "/home/ubuntu/.local/lib/python3.10/site-packages/vllm/engine/llm_engine.py", line 700, in _run_workers
    output = executor(*args, **kwargs)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/vllm/worker/worker.py", line 70, in init_model
    self.model = get_model(self.model_config)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/vllm/model_executor/model_loader.py", line 93, in get_model
    model = model_class(model_config.hf_config, quant_config)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/vllm/model_executor/models/mistral.py", line 268, in __init__
    self.model = MistralModel(config, quant_config)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/vllm/model_executor/models/mistral.py", line 226, in __init__
    self.layers = nn.ModuleList([
  File "/home/ubuntu/.local/lib/python3.10/site-packages/vllm/model_executor/models/mistral.py", line 227, in <listcomp>
    MistralDecoderLayer(config, quant_config)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/vllm/model_executor/models/mistral.py", line 170, in __init__
    self.mlp = MistralMLP(
  File "/home/ubuntu/.local/lib/python3.10/site-packages/vllm/model_executor/models/mistral.py", line 62, in __init__
    self.gate_up_proj = ParallelLinear.column(hidden_size,
  File "/home/ubuntu/.local/lib/python3.10/site-packages/vllm/model_executor/layers/quantized_linear/__init__.py", line 17, in column
    return ColumnParallelLinear(*args, **kwargs)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/vllm/model_executor/parallel_utils/layers.py", line 138, in __init__
    self.create_weights(params_dtype)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/vllm/model_executor/parallel_utils/layers.py", line 150, in create_weights
    torch.empty(self.output_size_per_partition,
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 448.00 MiB (GPU 0; 14.58 GiB total capacity; 13.91 GiB already allocated; 404.50 MiB free; 13.91 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
```

**Comment by jeffreymeetkai** [comment]
Hi, regarding this problem, can you try this command `python server_vllm.py --model meetkai/functionary-7b-v1.4 --max-model-len 4096 --gpu-memory-utilization 0.95`?

This problem should be due to the way vLLM sets up and allocates the KV cache between GPU and CPU during initialization. By reducing the max_model_len from Mistral's default of 32k to 4k and increasing gpu-memory-utilization slightly to 0.95, the KV cache can be initialized successfully. I tested with both 4k and 8k context windows on an A4000 and both works. Alternatively, any GPU >= 20GB VRAM will work for the default 32k context window.

Let me know if you encounter any other error from this. Thanks!

**Comment by tonylampada** [comment]
I tried but still got the same error.
But hey never mind. I was able to run it from CPU using the latest instructions you added in the README.
Thank you, really appretiate it.
